name: ShadowBedwars
version: ${project.version}
main: uk.co.tmdavies.shadowbedwars.ShadowBedwars
api-version: 1.16
authors: [Carbonate]
description: Private Bedwars Plugin
website: https://www.tmdavies.co.uk
commands:
  bedwarsadmin:
    aliases: [bwadmin, bwa, sbwa, sbwadmin]
permissions:
  shadowbedwars.admin:
    default: op
